services:
  prometheus:
    image: docker.io/prom/prometheus
    # container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus:z
      - prom_data:/prometheus:z


volumes:
  prom_data: