version: '3'

services:
  db:
    image: postgres:14.0
    container_name: db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - db_volume:/var/lib/postgresql
    networks:
      - backend_network
  pgadmin:
    image: dpage/pgadmin4:6.1
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@your-netcup-domain.net
      - PGADMIN_DEFAULT_PASSWORD=secret
      - PGADMIN_LISTEN_PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - pgadmin_volume:/var/lib/pgadmin
    networks:
      - backend_network
volumes:
  db_volume:
  pgadmin_volume:
networks:
  backend_network:
    driver: bridge


# This Docker Compose setup is based on:
# Patrick Weber, netcup tutorial (https://community.netcup.com/en/tutorials/how-to-install-postgres-and-pgadmin-with-docker-and-connect-pgadmin-with-postgres)
